name: Clang Build + Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build+test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make clang
      run: make -C cicd_build/ clang_validation
    - name: test clang
      run: cicd_build/a.out
